services:
  mysql_container:
    image: mysql
    ports:
      - 5050:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - .:/docker-entrypoint-initdb.d
